namespace EliteTrader.EliteOcr.Enums
{
    public enum EnumCommodityCategory
    {
        Chemicals = 1,
        ConsumerItems = 2,
        LegalDrugs = 3,
        Foods = 4,
        IndustrialMaterials = 5,
        Medicines = 6,
        Metals = 7,
        Minerals = 8,
        Technology = 9,
        Weapons = 10,
        Waste = 11,
        Machinery = 12,
        Textiles = 13,
        Slavery = 15,
    }

    public enum EnumStationType
    {
        Unknown = 0,
        CoriolisStation = 1,
        ONeillStation = 2,
        OcellusStation = 3,
        OrbisStation = 4,
        CommercialOutpost = 5,
        IndustrialOutpost = 6,
        ScientificOutpost = 7,
        UnsanctionedOutpost = 8,
        CivilianOutpost = 9,
        Militaryoutpost = 10,
        UnsanctionedCivilianOutpost = 11,
        MiningOutpost = 12,
    }

    public enum EnumCommodityItemName
    {
        Unknown = 0,
        Explosives = 1,
        Pesticides = 2,
        MineralOil = 3,
        HydrogenFuel = 4,
        DomesticAppliances = 5,
        ConsumerTechnology = 6,
        Clothing = 7,
        Liquor = 8,
        Coffee = 9,
        Tea = 10,
        FoodCartridges = 12,
        Fish = 13,
        AnimalMeat = 14,
        Grain = 15,
        Algae = 16,
        CropHarvesters = 19,
        MicrobialFurnaces = 20,
        MineralExtractors = 21,
        MarineEquipment = 22,
        BasicMedicines = 23,
        Aluminium = 24,
        Gold = 25,
        Tantalum = 26,
        Titanium = 27,
        Cobalt = 28,
        Coltan = 29,
        Bauxite = 30,
        Rutile = 31,
        ComputerComponents = 32,
        LandEnrichmentSystems = 33,
        AquaponicSystems = 34,
        AnimalMonitors = 35,
        Robotics = 36,
        Leather = 38,
        Biowaste = 39,
        Scrap = 40,
        PersonalWeapons = 41,
        Narcotics = 43,
        CombatStabilisers = 44,
        AgriMedicines = 45,
        ProgenitorCells = 46,
        Bertrandite = 47,
        AutoFabricators = 48,
        BioreducingLichen = 49,
        ResonatingSeparators = 50,
        AdvancedCatalysers = 51,
        HESuits = 52,
        NonLethalWpns = 53,
        ReactiveArmour = 54,
        PerformanceEnhancers = 55,
        Indite = 56,
        Gallite = 57,
        Lepidolite = 58,
        Beer = 59,
        SyntheticMeat = 60,
        FruitandVegetables = 61,
        Superconductors = 62,
        Silver = 63,
        Lithium = 64,
        Palladium = 65,
        Indium = 66,
        Uranium = 67,
        Gallium = 68,
        Beryllium = 69,
        Polymers = 70,
        Semiconductors = 71,
        Copper = 72,
        NaturalFabrics = 73,
        SyntheticFabrics = 74,
        Tobacco = 75,
        Wine = 77,
        Uraninite = 78,
        BattleWeapons = 79,
        AtmosphericProcessors = 80,
        PowerGenerators = 82,
        WaterPurifiers = 83,
        Platinum = 84,
        ChemicalWaste = 89,
        ImperialSlaves = 92,
        Slaves = 93,

        Rare = 200,
    }
}